const actionTypes = {
  ACT_GET_DETAIL_BY_ID: 'project/ACT_GET_DETAIL_BY_ID',
  ACT_CREATE: 'project/ACT_CREATE',
  ACT_GET_PROJECT_BY_ID: 'project/ACT_GET_PROJECT_BY_ID',
  ACT_UPDATE_PROJECT_BY_ID: 'project/ACT_UPDATE_PROJECT_BY_ID',
  ACT_FETCH_GET_ALL_PROJECTS: 'project/FETCH_GET_ALL_PROJECTS',
  ACT_FETCH_DELETE_PROJECT: 'project/FETCH_DELETE_PROJECT',
};

export default actionTypes;
